spring:
  application:
    name: CONSUMER-USER
  cloud:
    config:
      name: CONSUMER-USER, EUREKA-CLIENT

eureka:
  client:
    register-with-eureka: false

feign:
  hystrix:
    enabled: true


#ribbon:
#  eureka:
#    enabled: true
