
server:
  port: 8081

spring:
  application:
    name: CONSUMER-USER
#  cloud:
#    config:
#      name: CONSUMER-USER

eureka:
  client:
    register-with-eureka: false

ribbon:
  eureka:
    enabled: true


name: liwenhui