server:
  port: 7070

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:7070/eureka/

spring:
  application:
    name: EUREKA-SERVER
#  cloud:
#    config:
#      name: EUREKA-SERVER-NODE1
