server:
  port: 9091

spring:
  application:
    name: PROVIDER-USER
  mvc:
    throw-exception-if-no-handler-found: true
    http:
      encoding:
        force-request: true
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.146.55:3306/my-order?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    #    url: ENC(wZqzrIh2/A+VeIssX35GqYBMWECuUW9Y8i1K8fY34QvquoMRQvmEKP1dxPl/7o5oO250RFHJ+ctijjuVGdh1sDjP3u2b/Dkcg9eG6l9GGLoAmBpIU0ZECQvnr9MWbGs1nRR8VR457QI=)
    #    username: ENC(83KoAUP7BQA5GRSqejSgqrD0wqBw47y6)
    #    password: ENC(87D1u+uXaRzYP80xkYwzdgryMw9Q+vAG)
    validationQuery: SELECT 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/,http://localhost:7071/eureka/
  instance:
    instance-id: PROVIDER-USER-9091 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址

info: #微服务详细信息
  app.name: booking
  author: liwenhui
  description: 用户模块提供方

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

regCenter:
  serverList: 120.78.146.55:2181
  namespace: elastic-job

simpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
